apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projeto-analista-infra
  namespace: argocd
spec:
  project: default
  source:
    # SUBSTITUA PELA URL DO SEU REPOSITÓRIO GITHUB
    repoURL: "https://github.com/lucascardosobarbeiro/projetos-devops.git"
    targetRevision: HEAD
    path: k8s-config/app-manifests # Pasta onde estão os YAMLs do app
  destination:
    server: "https://kubernetes.default.svc"
    namespace: app-producao # Namespace onde o app vai rodar
  syncPolicy:
    automated: # Configura o SELF-HEALING
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Cria o namespace 'app-producao' se não existir
